### ISSUE TITLE
No handler for "/my-web-archive"

### ISSUE THREAD

**Issue by mariomadproductions** [webrecorder/pywb#406] opened 2018-11-10 09:44 UTC
## Describe the bug
When running pywb by following the instructions [here](https://pywb.readthedocs.io/en/latest/manual/usage.html#using-pywb-recorder), I get the error "No handler for "/my-web-archive"" in the browser

## Steps to reproduce the bug
Follow the instructions [here](https://pywb.readthedocs.io/en/latest/manual/usage.html#using-pywb-recorder).

## Expected behavior
The website should load as normal with pywb "recording" the websie.

## Environment

- OS: Raspbian GNU/Linux 9
- Browser Chromium
- Version: I used `pip install pywb` a couple of days ago

**Comment by ikreymer** [comment] 2018-11-10 15:42
Was there any output after you ran: `wb-manager init my-web-archive` ?

Note that you need to be in the same working directory to when you run `wayback` as where you ran `wb-manager` (the docs can probably be made more clear on this).

Here's a log of when I run this locally. I can the load `http://localhost:8080/my-web-archive/record/http://example.com/` to start recording.

```
$ mkdir pywb-test
$ cd pywb-test/
$ wb-manager init my-web-archive
2018-11-10 07:38:50,318: [INFO]: Created Directory: /tmp/pywb-test/collections/my-web-archive
2018-11-10 07:38:50,318: [INFO]: Created Directory: /tmp/pywb-test/collections/my-web-archive/archive
2018-11-10 07:38:50,318: [INFO]: Created Directory: /tmp/pywb-test/collections/my-web-archive/indexes
2018-11-10 07:38:50,318: [INFO]: Created Directory: /tmp/pywb-test/collections/my-web-archive/static
2018-11-10 07:38:50,319: [INFO]: Created Directory: /tmp/pywb-test/collections/my-web-archive/templates
2018-11-10 07:38:50,320: [INFO]: Created Directory: /tmp/pywb-test/static
2018-11-10 07:38:50,320: [INFO]: Created Directory: /tmp/pywb-test/templates
$ wayback --record --live -a --auto-interval 10
[Errno 2] No such file or directory: './config.yaml'
2018-11-10 07:38:59,572: [INFO]: Auto-Indexing Enabled on "/tmp/pywb-test/collections", checking every 10 secs
2018-11-10 07:38:59,673: [INFO]: Starting Gevent Server on 8080
2018-11-10 07:38:59,675: [INFO]: Checking Collection: my-web-archive
```

**Comment by mariomadproductions** [comment] 2018-11-10 15:57
```
$ wb-manager init test-2018_11_10-15_52:
[2018-11-10 15:52:18,060: [INFO]: Created Directory: /home/pi/collections/test-2018_11_10-15_52
2018-11-10 15:52:18,061: [INFO]: Created Directory: /home/pi/collections/test-2018_11_10-15_52/archive
2018-11-10 15:52:18,062: [INFO]: Created Directory: /home/pi/collections/test-2018_11_10-15_52/indexes
2018-11-10 15:52:18,063: [INFO]: Created Directory: /home/pi/collections/test-2018_11_10-15_52/static
2018-11-10 15:52:18,064: [INFO]: Created Directory: /home/pi/collections/test-2018_11_10-15_52/templates
2018-11-10 15:52:18,065: [INFO]: Created Directory: /home/pi/static
2018-11-10 15:52:18,066: [INFO]: Created Directory: /home/pi/templates
```

**Comment by ikreymer** [comment] 2018-11-10 16:03
If you call the collection `test-2018_11_10-15_52`, then you should be able to record by loading:
`http://localhost:8080/test-2018_11_10-15_52/record/http://example.com/`

**Comment by mariomadproductions** [comment] 2018-11-10 16:10
That works. For some reason it didn't before. However when try to archive the site I'm interested, it doesn't work. This site is a https one that needs a specific user agent and client certificate. It works fine if I don't have the ``http://localhost:8080/test-2018_11_10-15_52/record/`` prefix in the URL.

**Comment by ikreymer** [comment] 2018-11-14 21:33
Hm, pywb should be proxying the user-agent and headers exactly from the browser. If you run with `--debug`, there may be more info printed in the logs. It's hard to say exactly what the issue is as it may be specific to this url. You can also try running pywb proxy mode, if you have to have a custom client certificate, that may be required. Please open a new issue or you can also email us at support [at] webrecorder.io if you'd like us to try to repro the issue without sharing the url publicly.

Closing this as original issue has been fixed.

**Closed by ikreymer** 2018-11-14 21:33 UTC
