### ISSUE TITLE
wb-manager collection indexing error

### ISSUE THREAD

**Issue by despens** [webrecorder/pywb#709] opened 2022-04-12 11:16 UTC
## Describe the bug

Using `wb-manager <collection> reindex` on a browsertrix crawled collection (`--newContext page`)  prints thousands of lines on the console with the python error

```
'list' object has no attribute 'items'
```

The index.cdxj file is generated anyway, but unclear if complete.

## Steps to reproduce the bug

Drop warc files from browsertrix crawl into collection and run reindexing command as shown above.

## Expected behavior

All warc files should be reindexed without error.

## Environment

pywb 2.6.6 (installed via pip)
Python 3.8.10
Ubuntu 20.04

## Additional context

This only seems to happen when a crawl is made via browsertrix. If a collection solely contains warc files from other sources no error message appears. If a collection is containing both browsertrix and non-browsertrix warcs, only the browsertrix warcs cause this error to appear.

**Comment by ikreymer** [comment] 2022-04-15 04:22
The message is mostly ignorable in this case, but have a better fix in 2.6.7. The issue is the post-to-get conversion of JSON arguments didn't correctly handle lists (in pywb, but did in cdxj-indexer). This will now be fixed in 2.6.7 and also will print a better error if not parseable.

**Closed** 2022-04-15 04:30 UTC
