### ISSUE TITLE
No rewritig of <script type="text/javascript" src="http://code.jquery.com/jquery-1.6.3.min.js"></script>

### ISSUE THREAD

**Issue by steph-nb** [webrecorder/pywb#756] opened 2022-08-29 13:02 UTC
## Describe the bug
A web page in our collection (Seed: http://www.shvr.ch/ ; dating from 2014) contains this snippet:
<script type="text/javascript" src="http://code.jquery.com/jquery-1.6.3.min.js"></script>

Unfortunately the URL is not getting rewritten, which is resulting in a blocked live leak (Refused to load the script 'http://code.jquery.com/jquery-1.6.3.min.js' because it violates the following Content Security Policy directive: "default-src 'unsafe-eval' 'unsafe-inline' 'self' data: blob: mediastream: ws: wss:". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.)

## Expected behavior
The URL should be rewritten to something like (in my setup):
http://localhost:8080/orig/20140725113002/http://code.jquery.com/jquery-1.6.3.min.js

## Environment
- OS: Windows 10
- Browser :chrome
- Version: 100.0.4896.60

## Additional context
OpenWayback perfectly rewrites the URL.

**Comment by ikreymer** [comment] 2022-08-29 21:35
Are you able to share access to the replay or the WARC files that this is loaded from? Otherwise, not much we can look at, as this doesn't happen in current version of the site. Generally this type of rewriting works very well, so curious about this particular edge case..

**Comment by steph-nb** [comment] 2022-08-30 06:17
Hi Ilya,
sure, I uploaded to webrecorder.io:
https://conifer.rhizome.org/webmiriam/rewriting/20140725113019/http://www.shvr.ch/

Many thanks and BR

**Comment by ikreymer** [comment] 2022-08-30 06:36
Have you tried it with the latest version of pywb? I haven't been able to repro the issue, it could have been fixed in an older version of our tools. The Conifer service is being run by Rhizome. The rewriting is working correctly on the latest version, and the issue is likely due to missing html tag, eg.
```
<!DOCTYPE html>
<html>
<head>
...
</html>
```

**Comment by steph-nb** [comment] 2022-08-30 06:48
Hmm, I used version 2.6.7.
this is the last release, no?

**Comment by steph-nb** [comment] 2022-08-30 07:36
Or is my python too old?
I'm using python 3.6.1

**Comment by steph-nb** [comment] 2022-08-30 12:05
I could replay it successfully in https://replayweb.page/ and with the ArchiveWeb.page extension (after having it converted from arc.gz to warc.gz).
But no success in any way in pywb. Not even in pywb 2.6.8

**Comment by ikreymer** [comment] 2022-08-30 15:16
Could you upload the original file somewhere and send a link? Can send via e-mail if you'd like

**Comment by steph-nb** [comment] 2022-08-31 06:24
> Could you upload the original file somewhere and send a link? Can send via e-mail if you'd like

OK, I sent you a link by e-mail.

**Closed** 2022-08-31 23:51 UTC

**Comment by ikreymer** [comment] 2022-09-01 05:33
Should be fixed in 2.6.8, added a test for this particular edge-case.

**Comment by steph-nb** [comment] 2022-09-01 09:00
Many thanks Ilya, works like a charm :-)
