### ISSUE TITLE
Replaying Twitter: TypeError from pywb.js

### ISSUE THREAD

**Issue by rebeccacremona** [webrecorder/pywb#569] opened 2020-06-15 15:15 UTC
When replaying captures of the newly-redesigned Twitter (e.g., 
[LNN8-Q2W8.warc.gz](https://github.com/webrecorder/pywb/files/4780937/LNN8-Q2W8.warc.gz), `pywb.js:19:16187` throws `TypeError: can't convert symbol to string`, which causes the replaying JS to bork, so you only end up with Twitter's generic, "Something went wrong" message.

No such error, and it plays back correctly, in Webrecorder Desktop App 2.0.1, and Webrecorder Player 1.8.0.

Same error, preventing successful capture and playback, with a local Webrecorder, built from master, from the latest pywb image (FROM webrecorder/pywb:develop@sha256:9cb1b077058bd5ee9fa2d753c5d80584d2f8dd7d6b93d76998d6c8042fc8ff13).

replayweb.page also fails, with a similar JS error:
```
Uncaught (in promise) Error: Unexpected input given to normalize. Expected type to be "object", found "string".
    at k (vendors~main.55bd4704.js:36)
    at U (main.5c0baa34.js:12)
    at main.5c0baa34.js:12
```

This can be finicky to reproduce, since Twitter is also rate-limiting pretty aggressively.

Happy to help debug/fix, though I'm still pretty unfamiliar with the intricacies of pywb.js

**Comment by ikreymer** [comment] 2020-06-15 15:39
Thanks for identifying this! Yes, the rate limiting is pretty aggressive these days, and the rate limit error looks similar to this too, though slightly more loads I think. Will take a look!

**Comment by rebeccacremona** [comment] 2020-06-15 17:16
Thanks Ilya! In case it's convenient, here's a warc with a single rate-limited capture: 
[S7DL-UC7L.warc.gz](https://github.com/webrecorder/pywb/files/4781849/S7DL-UC7L.warc.gz) Much smaller warc, playback in the Webrecorder app displays the rate-limiting message (which Twitter has disappear after a second or two).

**Comment by ikreymer** [comment] 2020-06-15 17:29
The issue is that an OPTIONS request is accidentally getting indexed, which it shouldn't be.
This is actually not an issue when adding the WARC via `wb-manager add`, as the `-p` - append POST query also takes care of OPTIONS requests.
But, this flag is not enabled by default probably for perma indexing, and, there also seems to be a bug in replayweb.page due to a typo that causes it to not ignore OPTIONS, will look at that.

At this point, probably OPTIONS requests should always be ignored w/o any additional flags, so leaving this open as a reminder of that..

**Comment by rebeccacremona** [comment] 2020-06-15 18:37
For the historical record: ignore my report that the master branch of WR + latest pywb/develop Docker image exhibited this problem on this day. It doesn't. I made a git error and had the wrong commit checked out 🙄

**Comment by ikreymer** [comment] 2020-07-14 22:17
Closing as it has been sufficiently addressed: was a perma.cc-specific issue, and also addressed OPTIONS in replayweb.page

**Closed by ikreymer** 2020-07-14 22:17 UTC
