### ISSUE TITLE
Fails to re-write some URLs when replaying recent archives of http://www.bcg.com/

### ISSUE THREAD

**Issue by anjackson** [webrecorder/pywb#676] opened 2021-11-08 15:17 UTC
## Expected behavior

The page is https://www.bcg.com/ an when we replay it, we get content from our homepage inserted into it.

## What actually happened

See https://github.com/ukwa/ukwa-pywb/issues/70 - seems some dynamic content inclusion is slipping past Wombat?

## Browser

Reproduced in various desktop browsers.

**Comment by ikreymer** [comment] 2021-11-12 06:39
Caused by rewritten `data-` attributes.
Disabled rewriting of `data-` attributes, as accessing them via `dataset` property was not being handled in wombat.
Started to fix in wombat, but realized would be better to not rewrite them at all.
Fixed in 2.6.1

**Closed by ikreymer** 2021-11-12 06:39 UTC
