### ISSUE TITLE
feature request: show index and allow to use wildcards on the search query

### ISSUE THREAD

**Issue by dportabella** [webrecorder/pywb#301] opened 2018-02-21 16:37 UTC
For the small archive cases, it would be interesting to have the option to show a list of all the archives.

Also, as done with the [CommonCrawl index server](http://index.commoncrawl.org/CC-MAIN-2018-05), it would be great if we can use search using wildcards. For example, searching example.com/* could list http://example.com/page1.html and http://example.com/page2.html

**Comment by ikreymer** [comment] 2018-02-22 23:09
The same options are there, the endpoint has changed slightly, and probably need better docs!

For a collection `test`, you can access the cdx server endpoint at `http://localhost:8080/test/cdx` and run queries like: `http://localhost:8080/test/cdx?url=example.com/&matchType=prefix`

using the [CDXJ Server API](http://pywb.readthedocs.io/en/latest/manual/cdxserver_api.html#api-reference)

**Comment by dportabella** [comment] 2018-02-23 06:44
that's cool, thx! however I am talking about the user interface, not about an API.

the user can go to [this page](http://index.commoncrawl.org/CC-MAIN-2018-05), fill-up the field with `example.cpm/*` and will get the matching records in a web page that he can click on and see the archive.

an about the first feature request "the option to show a list of all the archives", I meant that the homepage lists all the archives, and that the user can click on and the see archived page.

**Comment by Serkan-devel** [comment] 2018-09-28 23:58
any updates on this?

**Comment by mcepl** [comment] 2018-10-02 15:34
Apparently, I have came with the same idea in https://lwn.net/Articles/767382/ :(

**Comment by N0taN3rd** [comment] 2019-02-19 23:20
This functionality was added in PR #421

**Comment by ikreymer** [comment] 2019-02-28 19:46
Released with 2.2.x! You should be able to do a query like: http://localhost:8080/pywb/*/http://iana.org/* with the sample data.
See #421 for more info on the new query UI

**Closed by ikreymer** 2019-02-28 19:46 UTC
Labels: documentation

**Comment by taylor-schneider** [comment] 2023-06-26 23:30
@ikreymer Is this actually working? I am testing with version 2.7.4 and I am not able to reproduce the behavior you mention. Nor am I seeing the behavior mentioned in #421
