### ISSUE TITLE
[2.7.0] Header for "undated" access not fully functional

### ISSUE THREAD

**Issue by bricas** [webrecorder/pywb#779] opened 2022-11-24 14:44 UTC
On a typical archived page view (`https://<site>/<collection>/<date>/<url>`), the header shows "Current Capture" information, and you can view the calendar and timeline for navigation.

If you visit the pywb instance with an undated url  (`https://<site>/<collection>/<url>`), which I believe brings up the most recent capture (please correct me if this isn't the case!) the capture information isn't displayed and the calendar and timeline functions do not work.

Weirdly, if i navigate to another page and then press "back" (twice), it redirects me to a dated capture and everything works as expected.

**Comment by tw4l** [comment] 2022-11-24 17:03
Thanks @bricas ! At first pass on Chromium I'm unable to reproduce this issue -  entering `https://<site>/<collection><url>` (in the browser) redirects to the latest capture (e.g. `http://localhost:8080/ukwa/20221114104844/https://www.dpconline.org/`), and the calendar/timeline seem to be functioning fine.

Can you share some more information so I can try to reproduce? e.g. the browser you're running, the site - if you're able to share a screencast or cdx access to the collection that would be even better!

**Comment by tw4l** [comment] 2022-11-24 18:50
@bricas - Ilya just pointed out that there is a configuration option for the redirect to a timestamped URL - try adding `redirect_to_exact: true` to your `config.yaml` file.

I'm seeing the same behaviour as you when `redirect_to_exact` is omitted or false, but setting it to true seems to resolve the issue with the calendar and timeline. Will look into that but in the meantime that setting should resolve your issue!

**Comment by bricas** [comment] 2022-11-24 19:12
@tw4l indeed, that config option sends me to a url with a date and the issue goes away! Thanks!

**Comment by tw4l** [comment] 2022-12-06 20:38
This is now fixed in the upcoming 2.7.1 release so that the calendar and timeline render as expected regardless of the `redirect_to_exact` setting

**Closed by tw4l** 2022-12-06 20:38 UTC
